child_mortality:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /opt/dbt_data/dev.duckdb
      threads: 1
      extensions:
        - httpfs
      settings:
        s3_endpoint: "{{ env_var('MINIO_ENDPOINT', 'localhost:9000') }}"
        s3_access_key_id: "{{ env_var('MINIO_ROOT_USER') }}"
        s3_secret_access_key: "{{ env_var('MINIO_ROOT_PASSWORD') }}"
        s3_use_ssl: false
        s3_url_style: path
